GameWorld/GameWorld/Controllers/ClientController.cs
using GameWorld.Models.Client;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GameWorld.Domain;
using Microsoft.AspNetCore.Authorization;

namespace WebShopDemo.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ClientController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;

        public ClientController(UserManager<ApplicationUser> userManager)
        { this.userManager = userManager; }

        public async Task<IActionResult> Index()
        {
            var allUsers = this.userManager.Users
                .Select(u => new ClientIndexVM
                {
                    Id = u.Id,
                    UserName = u.UserName,
                    FirstName = u.FirstName,
                    LastName = u.LastName,
                    Address = u.Address,
                    PhoneNumber = u.PhoneNumber,
                    Email = u.Email
                }).ToList();

            var adminIds = (await this.userManager.GetUsersInRoleAsync("Administrator"))
                .Select(a => a.Id).ToList();
            foreach (var user in allUsers)
            {
                user.IsAdmin = adminIds.Contains(user.Id);
            }

            var users = allUsers.Where(x => x.IsAdmin == false)
                .OrderBy(x => x.UserName).ToList();

            return this.View(users);
        }

        public ActionResult Delete(string id)
        {
            var user = this.userManager.Users.FirstOrDefault(x => x.Id == id);

            if (user == null)
            { return NotFound(); }

            ClientDeleteVM userToDelete = new ClientDeleteVM()
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Address = user.Address,
                PhoneNumber = user.PhoneNumber,
                Email = user.Email,
                UserName = user.UserName
            };
            return View(userToDelete);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(ClientDeleteVM bindingModel)
        {
            string id = bindingModel.Id;
            var user = await userManager.FindByIdAsync(id);
            if (user == null)
            { return NotFound(); }

            else
            {
                IdentityResult result = await userManager.DeleteAsync(user);
                if (result.Succeeded)
                { return RedirectToAction("SuccessDeleteUser"); }
                else { return NotFound(); }
            }
        }
        public ActionResult SuccessDeleteUser()
        { return View(); }
    }
}

GameWorld/GameWorld/Controllers/ContactController.cs
using GameWorld.Data;
using GameWorld.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace GameWorld.Controllers
{
    public class ContactController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContactController(ApplicationDbContext context)
        {
            _context = context;
        }

        
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Submit(Contact contact)
        {

            contact.SubmittedAt = DateTime.Now;
            _context.Contacts.Add(contact);
            _context.SaveChanges();
            return RedirectToAction("ThankYou");
        }

        public ActionResult ThankYou()
        {
            return View();
        }

        [Authorize(Roles ="Administrator")]
        public ActionResult Messages()
        {
            //a list of all the messages in the database
            var messages = _context.Contacts.ToList();
            return View(messages);
        }
    }
}

GameWorld/GameWorld/Controllers/OrderController.cs
using GameWorld.Data;
using GameWorld.Domain;
using GameWorld.Models.Order;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace GameWorld.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _context;
        public OrderController(ApplicationDbContext context)
        { this._context = context; }

        [Authorize(Roles ="Administrator")]
        public IActionResult Index()
        {
            string userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _context.Users.SingleOrDefault(u => u.Id == userId);
            List<OrderIndexVM> orders = _context.Orders
                .Select(x => new OrderIndexVM
                {
                    Id = x.Id,
                    OrderDate = x.OrderDate.ToString("dd-MMM,yyyy hh:mm", CultureInfo.InvariantCulture),
                    UserId = x.UserId,
                    User = x.User.UserName,
                    ProductId = x.ProductId,
                    Product = x.Product.ProductName,
                    Image = x.Product.Image,
                    Platform = x.Product.Platform,
                    Quantity = x.Quantity,
                    Price = x.Price,
                    Discount = x.Discount,
                    TotalPrice = x.FinalPrice
                }).ToList();
            return View(orders);
        }
    
        [Authorize(Roles = "Client,Administrator")]
        public IActionResult MyOrders(string searchString)
        {
            string currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = this._context.Users.SingleOrDefault(u => u.Id == currentUserId); 
            if(user==null)
            { return null; }

            List<OrderIndexVM> orders = _context.Orders.Where(x => x.UserId == user.Id)
                .Select(x => new OrderIndexVM
                {
                    Id = x.Id,
                    OrderDate = x.OrderDate.ToString("dd-MMM,yyyy hh:mm", CultureInfo.InvariantCulture),
                    UserId = x.UserId,
                    User = x.User.UserName,
                    ProductId = x.ProductId,
                    Product = x.Product.ProductName,
                    Image = x.Product.Image,
                    Platform = x.Product.Platform,
                    Quantity = x.Quantity,
                    Price = x.Price,
                    Discount = x.Discount,
                    TotalPrice = x.FinalPrice
                }).ToList();

            if(!String.IsNullOrEmpty(searchString))
            { orders = orders.Where(o => o.Product.ToLower().Contains(searchString.ToLower())).ToList(); }
            return this.View(orders);

        }

        public ActionResult Create(int productId, int quantity)
        {
            string userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _context.Users.SingleOrDefault(u => u.Id == userId);
            var product = this._context.Products.SingleOrDefault(x => x.Id == productId);

            if(user==null || product==null || product.Quantity < quantity)
            { return this.RedirectToAction("Index", "Product"); }

            OrderConfirmVM orderForDb = new OrderConfirmVM
            {
                UserId = userId,
                User = user.UserName,
                ProductId = productId,
                ProductName = product.ProductName,
                Image = product.Image,
                Platform = product.Platform,
                Quantity = quantity,
                Price = product.Price,
                Discount = product.Discount,
                TotalPrice = quantity * product.Price - quantity * product.Price * product.Discount / 100
            };
            

            return View(orderForDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OrderConfirmVM bindingModel)
        {
            if (this.ModelState.IsValid)
            {
                string userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var user = _context.Users.SingleOrDefault(u => u.Id == userId);
                var product = this._context.Products.SingleOrDefault(x => x.Id == bindingModel.ProductId);

                if (user==null || product==null || product.Quantity<bindingModel.Quantity || bindingModel.Quantity ==0)
                { return this.RedirectToAction("Index", "Product"); }

                Order orderForDb = new Order
                {
                    OrderDate = DateTime.UtcNow,
                    ProductId = bindingModel.ProductId,
                    UserId = userId,
                    Quantity = bindingModel.Quantity,
                    Price = product.Price,
                    Discount = product.Discount
                };
                var AllPrice = orderForDb.Quantity * orderForDb.Price - orderForDb.Quantity * orderForDb.Price * orderForDb.Discount / 100;
                if (user.Balance >= AllPrice)
                {
                    user.Balance -= AllPrice;
                    product.Quantity -= bindingModel.Quantity;
                    this._context.Products.Update(product);
                    this._context.Orders.Add(orderForDb);
                }
                else 
                {
                    return this.RedirectToAction("NotEnoughBal", "Product");
                }

                this._context.SaveChanges();
            }
            return this.RedirectToAction("Index", "Product");
        }

        public IActionResult ThanksForBuying()
        { return this.View(); }
    }
}

GameWorld/GameWorld/Controllers/StatisticsController.cs
using GameWorld.Abstraction;
using GameWorld.Models.Statistics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameWorld.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class StatisticsController : Controller
    {
        private readonly IStatisticsService statisticsService;
        public StatisticsController(IStatisticsService statisticsService)
        { this.statisticsService = statisticsService; }
        public IActionResult Index()
        {
            StatisticsVM statistics = new StatisticsVM();
            statistics.CountClients = statisticsService.CountClients();
            statistics.CountProducts = statisticsService.CountProducts();
            statistics.CountOrders = statisticsService.CountOrders();
            statistics.SumOrders = (int)statisticsService.SumOrders();

            return View(statistics);
        }
    }
}

GameWorld/GameWorld/Views/Shared/_Layout.cshtml
<!DOCTYPE html>


<style>
    .navbar {
        background: #FFFFFF;
        border-radius: 20px;
        height: 65px;
        display: flex;
        justify-content: center;
    }

    .container-.navbar{
        border-radius: 20px;
    }
    .navbar {
  background: #FFFFFF;
  border-radius: 20px; 
  min-height: 65px;
  display: flex;
  justify-content: center;
  flex-wrap: wrap; 
}

.container.custom-container {
  padding-bottom: 60px;
  width: 100%; 
}


@@media (min-width: 576px) {
  .navbar-nav {
    flex-direction: row;
  }
}

@@media (max-width: 575px) {
  .navbar-brand,
  .navbar-nav {
    margin: 0;
  }

  .navbar-collapse {
    margin-top: 0;
    margin-bottom: 0;
  }

  .navbar-nav .nav-link {
    padding-top: 1rem;
    padding-bottom: 1rem;
  }
}


.gradient-custom
{
background: radial-gradient(circle at center, #6AC4FF, #D68EB2);
}

.custom-container{
    max-width: 1600px;
    margin: 0 auto;
    width: auto;
}

    .footer {
        padding: 20px 0;
        background-color: #f8f9fa;
        text-align: center;
        border-top: 1px solid #ccc;
    }
    .container.custom-container {
        padding-bottom: 60px;
    }

</style>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameWorld</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body class="gradient-custom">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 custom-container">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><strong>GW</strong></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        @if ((this.User.Identity.IsAuthenticated) && (this.User.IsInRole("Administrator")))
                        {
                            <li class="nav-item active">
                                <div class="dropdown show">
                                    <a class="nav-link active dropdown-toggle" href="e"
                                       id="dropdownMenuLink" data-toggle="dropdown"
                                       aria-haspopup="true" aria-expanded="false">
                                        Statistic Module
                                    </a>

                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                        <a class="dropdown-item" asp-controller="Client" asp-action="Index">Clients</a>
                                        <a class="dropdown-item" asp-controller="Order" asp-action="Index">Orders</a>
                                        <a class="dropdown-item" asp-controller="Statistics" asp-action="Index">Statistics</a>
                                        <a class="dropdown-item" asp-controller="Contact" asp-action="Messages">Messages</a>
                                    </div>

                                </div>
                            </li>
                        }
                    </ul>
                    <div class="navbar-search ml-auto">
                    <form asp-controller="Product" asp-action="Index" method="get">
                         <div class="input-group">
                           <input type="text" class="form-control" name="searchStringProductName" placeholder="Search for a product...">
                           <div class="input-group-append">
                           <button type="submit" class="btn btn-outline-primary">
                           <span class="button-text">Search</span>
                           </button>
                          </div>
                            </div>
                     </form>
                     </div>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <footer class=" footer text-muted">
        <div class="container" style="text-align: center;">
            &copy; 2023 - GameWorld - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> | <a asp-area="" asp-controller="Contact" asp-action="Index">Contact Us</a>
        </div>
    </footer>
    <div class="container custom-container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>