GameWorld/GameWorld/Models/Product/ProductCreateVM.cs
using GameWorld.Models.Category;
using GameWorld.Models.Maker;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GameWorld.Models.Product
{
    public class ProductCreateVM
    {
        public ProductCreateVM()
        {
            Makers = new List<MakerPairVM>();
            Categories = new List<CategoryPairVM>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [MaxLength]
        [Display(Name ="Product Name")]
        public string ProductName { get; set; }

        [Required]
        [Display(Name ="Maker")]
        public int MakerId { get; set; }
        public virtual List<MakerPairVM> Makers{ get; set; }
        [Required]
        [Display(Name = "Category")]
        public int CategoryId { get; set; }
        public virtual List<CategoryPairVM> Categories { get; set; }

        [Display(Name ="Image")]
        public string Image { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        [Display(Name = "Platform")]
        public string Platform { get; set; }

        [Display(Name = "Quantity")]
        public int Quantity { get; set; }

        [Display(Name = "Price")]
        public decimal Price { get; set; }

        [Display(Name = "Discount")]
        public decimal Discount { get; set; }
    }
}

GameWorld/GameWorld/Models/Product/ProductDeleteVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GameWorld.Models.Product
{
    public class ProductDeleteVM
    {
        [Key]
        public int Id { get; set; }
        [Display(Name ="Product Name")]
        public string ProductName { get; set; }
        public int MakerId { get; set; }
        [Display(Name = "Maker")]
        public string MakerName { get; set; }
        public int CategoryId { get; set; }
        [Display(Name = "Category")]
        public string CategoryName { get; set; }

        [Display(Name = "Image")]
        public string Image { get; set; }
        [Display(Name = "Description")]
        public string Description { get; set; }

        [Display(Name = "Platform")]
        public string Platform { get; set; }

        [Display(Name = "Quantity")]
        public int Quantity { get; set; }
        [Display(Name = "Price")]
        public decimal Price { get; set; }
        [Display(Name = "Discount")]
        public decimal Discount { get; set; }
    }
}

GameWorld/GameWorld/Controllers/BalanceController.cs
using GameWorld.Models.Client;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GameWorld.Domain;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using GameWorld.Data;

namespace GameWorld.Controllers
{
    public class BalanceController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public BalanceController(UserManager<ApplicationUser> userManager)
        { _userManager = userManager; }
        public IActionResult AddBalance()
        { return View(); }
        [HttpPost]
        public async Task<IActionResult> AddBalance(decimal amount)
        {
            var user = await _userManager.GetUserAsync(User);
            user.Balance += amount;
            await _userManager.UpdateAsync(user);
            return RedirectToAction("Index", "Home");
        }
    }
}

GameWorld/GameWorld/Controllers/OrderController.cs
using GameWorld.Data;
using GameWorld.Domain;
using GameWorld.Models.Order;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace GameWorld.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _context;
        public OrderController(ApplicationDbContext context)
        { this._context = context; }

        [Authorize(Roles ="Administrator")]
        public IActionResult Index()
        {
            string userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _context.Users.SingleOrDefault(u => u.Id == userId);
            List<OrderIndexVM> orders = _context.Orders
                .Select(x => new OrderIndexVM
                {
                    Id = x.Id,
                    OrderDate = x.OrderDate.ToString("dd-MMM,yyyy hh:mm", CultureInfo.InvariantCulture),
                    UserId = x.UserId,
                    User = x.User.UserName,
                    ProductId = x.ProductId,
                    Product = x.Product.ProductName,
                    Image = x.Product.Image,
                    Platform = x.Product.Platform,
                    Quantity = x.Quantity,
                    Price = x.Price,
                    Discount = x.Discount,
                    TotalPrice = x.FinalPrice
                }).ToList();
            return View(orders);
        }
    
        [Authorize(Roles = "Client,Administrator")]
        public IActionResult MyOrders(string searchString)
        {
            string currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = this._context.Users.SingleOrDefault(u => u.Id == currentUserId); 
            if(user==null)
            { return null; }

            List<OrderIndexVM> orders = _context.Orders.Where(x => x.UserId == user.Id)
                .Select(x => new OrderIndexVM
                {
                    Id = x.Id,
                    OrderDate = x.OrderDate.ToString("dd-MMM,yyyy hh:mm", CultureInfo.InvariantCulture),
                    UserId = x.UserId,
                    User = x.User.UserName,
                    ProductId = x.ProductId,
                    Product = x.Product.ProductName,
                    Image = x.Product.Image,
                    Platform = x.Product.Platform,
                    Quantity = x.Quantity,
                    Price = x.Price,
                    Discount = x.Discount,
                    TotalPrice = x.FinalPrice
                }).ToList();

            if(!String.IsNullOrEmpty(searchString))
            { orders = orders.Where(o => o.Product.ToLower().Contains(searchString.ToLower())).ToList(); }
            return this.View(orders);

        }

        public ActionResult Create(int productId, int quantity)
        {
            string userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _context.Users.SingleOrDefault(u => u.Id == userId);
            var product = this._context.Products.SingleOrDefault(x => x.Id == productId);

            if(user==null || product==null || product.Quantity < quantity)
            { return this.RedirectToAction("Index", "Product"); }

            OrderConfirmVM orderForDb = new OrderConfirmVM
            {
                UserId = userId,
                User = user.UserName,
                ProductId = productId,
                ProductName = product.ProductName,
                Image = product.Image,
                Platform = product.Platform,
                Quantity = quantity,
                Price = product.Price,
                Discount = product.Discount,
                TotalPrice = quantity * product.Price - quantity * product.Price * product.Discount / 100
            };
            

            return View(orderForDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OrderConfirmVM bindingModel)
        {
            if (this.ModelState.IsValid)
            {
                string userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var user = _context.Users.SingleOrDefault(u => u.Id == userId);
                var product = this._context.Products.SingleOrDefault(x => x.Id == bindingModel.ProductId);

                if (user==null || product==null || product.Quantity<bindingModel.Quantity || bindingModel.Quantity ==0)
                { return this.RedirectToAction("Index", "Product"); }

                Order orderForDb = new Order
                {
                    OrderDate = DateTime.UtcNow,
                    ProductId = bindingModel.ProductId,
                    UserId = userId,
                    Quantity = bindingModel.Quantity,
                    Price = product.Price,
                    Discount = product.Discount
                };
                var AllPrice = orderForDb.Quantity * orderForDb.Price - orderForDb.Quantity * orderForDb.Price * orderForDb.Discount / 100;
                if (user.Balance >= AllPrice)
                {
                    user.Balance -= AllPrice;
                    product.Quantity -= bindingModel.Quantity;
                    this._context.Products.Update(product);
                    this._context.Orders.Add(orderForDb);
                }
                else 
                {
                    return this.RedirectToAction("NotEnoughBal", "Product");
                }

                this._context.SaveChanges();
            }
            return this.RedirectToAction("Index", "Product");
        }

        public IActionResult ThanksForBuying()
        { return this.View(); }
    }
}

GameWorld/GameWorld/Controllers/ProductController.cs
using GameWorld.Abstraction;
using GameWorld.Domain;
using GameWorld.Models.Category;
using GameWorld.Models.Maker;
using GameWorld.Models.Product;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameWorld.Controllers
{
    [Authorize(Roles ="Administrator")]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly IMakerService _makerService;

        public ProductController(IProductService productService, ICategoryService categoryService, IMakerService makerService)
        {
            this._productService = productService;
            this._categoryService = categoryService;
            this._makerService = makerService;
        }

        public ActionResult Create()
        {
            var product = new ProductCreateVM();
            product.Makers = _makerService.GetMakers()
                .Select(x => new MakerPairVM()
                {
                    Id = x.Id,
                    Name = x.MakerName
                }).ToList();
            product.Categories = _categoryService.GetCategories()
                .Select(x => new CategoryPairVM()
                {
                    Id = x.Id,
                    Name = x.CategoryName
                }).ToList();
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([FromForm] ProductCreateVM product)
        {
            if (ModelState.IsValid)
            {
                var createdId = _productService.Create(product.ProductName, product.MakerId, product.CategoryId,
                    product.Image, product.Description, product.Platform, product.Quantity, product.Price, product.Discount);

                if (createdId)
                { return this.RedirectToAction("CreateSuccess"); }
            }
            return View();
        }
        public IActionResult CreateSuccess()
        { return this.View(); }

        
        [AllowAnonymous]
        public IActionResult NotEnoughBal()
        { return this.View(); }

        [AllowAnonymous]
        public ActionResult Index(string searchStringCategoryName, string searchStringPlatformName, string searchStringProductName)
        {
            List<ProductIndexVM> products = _productService.GetProducts(searchStringCategoryName, searchStringPlatformName, searchStringProductName)
                .Select(product => new ProductIndexVM
                {
                    Id = product.Id,
                    ProductName = product.ProductName,
                    MakerId = product.MakerId,
                    MakerName = product.Maker.MakerName,
                    CategoryId = product.CategoryId,
                    CategoryName = product.Category.CategoryName,
                    Image = product.Image,
                    Description = product.Description,
                    Platform = product.Platform,
                    Quantity = product.Quantity,
                    Price = product.Price,
                    Discount = product.Discount

                }).ToList();
            return this.View(products);
        }

        public ActionResult Edit(int id)
        {
            Product product = _productService.GetProductById(id);
            if (product == null)
            { return NotFound(); }

            ProductEditVM updatedProduct = new ProductEditVM()
            {

                Id = product.Id,
                ProductName = product.ProductName,
                MakerId = product.MakerId,
                CategoryId = product.CategoryId,
                Image = product.Image,
                Description = product.Description,
                Platform = product.Platform,
                Quantity = product.Quantity,
                Price = product.Price,
                Discount = product.Discount
            };

            updatedProduct.Makers = _makerService.GetMakers()
                .Select(m => new MakerPairVM()
                {
                    Id = m.Id,
                    Name = m.MakerName
                }).ToList();

            updatedProduct.Categories = _categoryService.GetCategories()
                .Select(c => new CategoryPairVM
                {
                    Id = c.Id,
                    Name = c.CategoryName
                }).ToList();

            return View(updatedProduct);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Edit(int id, ProductEditVM product)
        {
            if (ModelState.IsValid)
            {
                var updated = _productService.Update(id, product.ProductName, product.MakerId,
                    product.CategoryId, product.Image, product.Description, product.Platform,
                    product.Quantity, product.Price, product.Discount);

                if (updated)
                { return this.RedirectToAction("Index"); }

            }
            return View(product);
        }

        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            Product item = _productService.GetProductById(id);
            if (item == null)
            { return NotFound(); }

            ProductDetailsVM product = new ProductDetailsVM()
            {
                Id = item.Id,
                ProductName = item.ProductName,
                MakerId = item.MakerId,
                MakerName = item.Maker.MakerName,
                CategoryId = item.CategoryId,
                CategoryName = item.Category.CategoryName,
                Image = item.Image,
                Description = item.Description,
                Platform = item.Platform,
                Quantity = item.Quantity,
                Price = item.Price,
                Discount = item.Discount
            };
            return View(product);
        }

        public ActionResult Delete(int id)
        {
            Product item = _productService.GetProductById(id);
            if (item == null)
            { return NotFound(); }

            ProductDeleteVM product = new ProductDeleteVM()
            {
                Id = item.Id,
                ProductName = item.ProductName,
                MakerId = item.MakerId,
                MakerName = item.Maker.MakerName,
                CategoryId = item.CategoryId,
                CategoryName = item.Category.CategoryName,
                Image = item.Image,
                Description = item.Description,
                Platform = item.Platform,
                Quantity = item.Quantity,
                Price = item.Price,
                Discount = item.Discount
            };
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            var deleted = _productService.RemoveById(id);
            if (deleted)
            { return this.RedirectToAction("DeleteSuccess"); }
            else { return View(); }
        }

        public IActionResult DeleteSuccess()
        { return View(); }
    }
}

GameWorld/GameWorld/Views/Product/Create.cshtml
@model GameWorld.Models.Product.ProductCreateVM

@{
    ViewData["Title"] = "Create";
}

<style>
   

#product form {
  background-color: #fff;
  border-radius: 20px;
  box-shadow: 0px 0px 5px 0px rgba(0, 0, 0, 0.2);
  padding: 50px;
  justify-content :center;
  width: 800px; /* increase the width to your desired size */
  display: inline-block;
  flex-direction: column;
  align-items: center;
}

#product form label {
  font-size: 18px;
  font-weight: bold;
  margin-bottom: 10px;
}

#product form input[type="text"],
#product form input[type="number"] {
  width: 100%;
  padding: 10px;
  margin-bottom: 20px;
  border: none;
  border-bottom: 2px solid #ccc;
  transition: all 0.2s ease-in-out;
  font-size: 16px;
}

#product form input[type="text"]:focus,
#product form input[type="number"]:focus {
  border-bottom: 2px solid #8d8d8d;
  outline: none;
}

#product form button {
  background-color: #2c3e50;
  color: #fff;
  padding: 10px 20px;
  border: none;
  border-radius: 3px;
  font-size: 16px;
  cursor: pointer;
  transition: all 0.2s ease-in-out;
}

#product form button:hover {
  background-color: #1b2631;
}

/* Add margin to the body to add spacing */
.body-product-specific {
  margin: 90px;
  text-align: center; /* center the content horizontally */
}

</style>
<h1>Create a new product!</h1>


<hr />
<body class="body-product-specific">

<div id="product" class="row">
    <div id="product" class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MakerId" class="control-label"></label>
                
                <select asp-for="MakerId" class="form-control text-center">
                    @foreach (var maker in Model.Makers)
                    {
                        <option value="@maker.Id">@maker.Name</option>
                    }
                </select>
                <span asp-validation-for="MakerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
               
                <select asp-for="CategoryId" class="form-control text-center">
                    @foreach (var category in Model.Categories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Platform" class="control-label"></label>
                <input asp-for="Platform" class="form-control" />
                <span asp-validation-for="Platform" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-light">Back to List</a>
</div>
</body>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GameWorld/GameWorld/Views/Product/CreateSuccess.cshtml
@*
@{ 
    ViewData["Title"] = "CreateSuccess";
}

<h1>You successfully added a product</h1>
<div>
    <a asp-action="Create" class="btn btn-light">Add a new product</a>
</div>

<div>
    <a asp-action="Index" class="btn btn-light">List all</a>
</div>*@


@{ 
    ViewData["Title"] = "Thank you for your purchase";
}
 <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Bootstrap 5 Thank You Example</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <style>
        .card {
            position: absolute;
            left: 50%;
            transform: translate(-45%);
            width: 80%;

            position: relative;
            margin-top: 10%;
            margin-bottom: 10%;
            width: 80%;
            min-height: 70vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        
        }
        .p-space{
        padding:5px;
    }
    </style>

    <body class="gradient-custom">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6">
                    <div class="card bg-white shadow p-5">
                        <div class="mb-4 text-center">
                            <svg xmlns="http://www.w3.org/2000/svg" class="text-success bi bi-check-circle" width="75" height="75"
                                 fill="currentColor" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z" />
                            </svg>
                        </div>
                        <div class="text-center">
                            <h1>You successfully added a product!</h1>
                            <p class="p-space"></p>
                            
                            <hr>
                            <a asp-action="Create" class="btn btn-info">Add a new product</a>
                            <p class="p-space"></p>
                           <a asp-action="Index" class="btn btn-info ">List all</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
    @{
    ViewBag.Title = "Thank You";
}

GameWorld/GameWorld/Views/Product/Delete.cshtml
@model GameWorld.Models.Product.ProductDeleteVM

@{
    ViewData["Title"] = "Delete";
}
<style>
    #container-round-white {
    background-color: #FFFFFF;
    border-radius: 15px;
    padding: 20px;
    height: auto; 
}
</style>
<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductDeleteVM</h4>
    <hr />
    <dl class="row" id="container-round-white">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MakerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MakerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MakerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MakerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Platform)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Platform)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GameWorld/GameWorld/Views/Product/DeleteSuccess.cshtml
@{ 
    ViewData["Title"] = "Thank you for your purchase";
}
 <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Bootstrap 5 Thank You Example</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <style>
        .card {
            position: absolute;
            left: 50%;
            transform: translate(-45%);
            width: 80%;

            position: relative;
            margin-top: 10%;
            margin-bottom: 10%;
            width: 80%;
            min-height: 70vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        
        }
        .p-space{
        padding:5px;
    }
    </style>

    <body class="gradient-custom">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6">
                    <div class="card bg-white shadow p-5">
                        <div class="mb-4 text-center">
                            <svg xmlns="http://www.w3.org/2000/svg" class="text-success bi bi-check-circle" width="75" height="75"
                                 fill="currentColor" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z" />
                            </svg>
                        </div>
                        <div class="text-center">
                            <h1>You successfully deleted a product!</h1>
                            <p class="p-space"></p>
                            
                            <hr>
                            <p class="p-space"></p>
                           <a asp-action="Index" class="btn btn-info ">List all products</a>
                           
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
    @{
    ViewBag.Title = "Thank You";
}

GameWorld/GameWorld/Views/Product/NotEnoughBal.cshtml
@using Microsoft.AspNetCore.Identity
@using GameWorld.Domain
@inject UserManager<ApplicationUser> UserManager
@{ 
    ViewData["Title"] = "Not enough balance";
}
<h1>Your balance isn't enough to place this order.</h1>
<div>
    <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("AddBalance", "Balance")'">Add more balance</button>
</div>

GameWorld/GameWorld/Views/Product/_OrderPartialView.cshtml
@model GameWorld.Models.Order.OrderConfirmVM

@*<form asp-controller="Order" asp-action="Create" method="get">
    <div class="d-flex align-items-center">
        <label class="font-weight-boldm text-left mr-1" asp-for="Quantity">Quantity:</label>
        <div class="mr-1">
            <input class="form-control" min="1" asp-for="Quantity" />
            <span asp-validation-for="Quantity" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-danger">Order</button>
    </div>
    <input type="hidden" asp-for="ProductId" value="@Model.ProductId" />
</form>

<form asp-controller="Order" asp-action="Create" method="get">
    <div class="d-flex align-items-center">
        <label class="font-weight-bold text-left mr-1" asp-for="Quantity">Quantity:</label>
        <div class="mr-1">
            <input class="form-control" type="number" min="1" asp-for="Quantity" />
            <span asp-validation-for="Quantity" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-danger">Order</button>
    </div>
    <input type="hidden" asp-for="ProductId" value="@Model.ProductId" />
</form>
*@

<form asp-controller="Order" asp-action="Create" method="get">
    <input type="hidden" asp-for="ProductId" value="@Model.ProductId" />
    <button type="submit" class="btn btn-danger">Order</button>
</form>